"""
MountainGuardian G03B – deterministic engine runtime smoke (NON-network).

Runs the frozen Risk Watch engine over:
  * the real tracked data/regions/jilong_port/region.json;
  * the G03A-derived 1991-2020 climatology references already present in the
    local runtime directory (generated by G03A; never re-downloaded here);
  * a deterministic normalized weather fixture built with the G03A
    normalize_weather contract (NO live Open-Meteo request is made).

The snapshot database is opened READ-ONLY for previous-state/trend lookup;
no snapshot is ever written by this smoke and no history is fabricated.

Usage (from the repository / worktree root):
    python tools/g03b_smoke.py [--runtime-dir DIR] [--retrieval-time ISO]
                               [--recent-mm X] [--forecast-mm Y] [--no-db]
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from riskwatch.climatology import ClimatologyStore  # noqa: E402
from riskwatch.engine import (  # noqa: E402
    compute_risk_watch,
    load_previous_state,
    query_historical_trend,
)
from riskwatch.region import load_region  # noqa: E402
from riskwatch.weather import normalize_weather  # noqa: E402


def build_fixture_payload(center: date, recent_mm: float, forecast_mm: float) -> dict:
    """Deterministic 14-day daily payload (today-7 .. today+6)."""
    times, precip = [], []
    day = center - timedelta(days=7)
    for i in range(14):
        times.append(day.isoformat())
        precip.append(recent_mm / 7.0 if i < 7 else forecast_mm / 7.0)
        day += timedelta(days=1)
    return {
        "latitude": None,
        "longitude": None,
        "generationtime_ms": 0.0,
        "utc_offset_seconds": 0,
        "timezone": "UTC",
        "timezone_abbreviation": "UTC",
        "elevation": None,
        "daily_units": {
            "time": "iso8601",
            "precipitation_sum": "mm",
            "temperature_2m_max": "degC",
            "temperature_2m_min": "degC",
        },
        "daily": {
            "time": times,
            "precipitation_sum": precip,
            "temperature_2m_max": [8.0] * 14,
            "temperature_2m_min": [-3.0] * 14,
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--runtime-dir",
        default=os.environ.get("MOUNTAINGUARDIAN_RUNTIME_DIR")
        or str(REPO_ROOT / "data" / "runtime"),
        help="G03A runtime dir holding climatology/ and the snapshot db",
    )
    parser.add_argument("--retrieval-time", default=None,
                        help="ISO retrieval instant (default: now UTC)")
    parser.add_argument("--recent-mm", type=float, default=55.0,
                        help="fixture recent 7-day cumulative precipitation")
    parser.add_argument("--forecast-mm", type=float, default=35.0,
                        help="fixture forecast 7-day cumulative precipitation")
    parser.add_argument("--no-db", action="store_true",
                        help="skip read-only snapshot db lookup")
    args = parser.parse_args(argv)

    runtime = Path(args.runtime_dir)
    region = load_region()
    store = ClimatologyStore(runtime / "climatology")

    climatologies = {}
    for point in region.monitoring_points:
        ref = store.load(point.point_id)
        if ref is None:
            print(
                f"SMOKE BLOCKED: no G03A climatology reference for "
                f"{point.point_id} under {runtime}. Materialize it with "
                "riskwatch.climatology first (this smoke never downloads)."
            )
            return 2
        climatologies[point.point_id] = ref

    retrieval_time = args.retrieval_time or datetime.now(timezone.utc).isoformat()
    center = date.fromisoformat(retrieval_time[:10])
    payload = build_fixture_payload(center, args.recent_mm, args.forecast_mm)

    weather = {}
    for point in region.monitoring_points:
        weather[point.point_id] = normalize_weather(
            payload, point, retrieval_time=retrieval_time,
            request_time=retrieval_time,
        )

    previous = None
    trend = None
    if not args.no_db:
        db_path = runtime / "mountainguardian.db"
        if db_path.is_file():
            from riskwatch.snapshot_store import SnapshotStore

            snapshot_store = SnapshotStore(db_path)
            try:
                previous = load_previous_state(snapshot_store, region.region_id)
                trend = query_historical_trend(snapshot_store, region.region_id)
            finally:
                snapshot_store.close()

    result = compute_risk_watch(
        region, weather, climatologies,
        previous=previous, run_id="g03b-smoke",
    )

    # Determinism proof: identical input -> byte-identical serialization.
    result2 = compute_risk_watch(
        region, weather, climatologies,
        previous=previous, run_id="g03b-smoke",
    )
    assert result.to_json() == result2.to_json(), "determinism violated"

    d = result.to_dict()
    print("=" * 72)
    print("G03B deterministic Risk Watch engine smoke (offline fixture)")
    print("=" * 72)
    print(f"algorithm_version : {d['algorithm_version']}")
    print(f"formula_version   : {d['formula_version']}")
    print(f"region            : {d['region_id']} "
          f"(config {d['provenance']['region_config_version']}, "
          f"scoring {d['provenance']['scoring_config_version']})")
    print(f"status            : {d['status']}")
    print(f"B  (static)       : {d['B']!r} -> display {d['B_rounded']} "
          f"(stored derived match: "
          f"{d['static_baseline']['stored_derived_match']})")
    for f in d["static_baseline"]["factor_contributions"]:
        print(f"    {f['factor_id']}: score {f['score_0_to_5']:.0f}/5 x "
              f"{f['normalized_weight_pct']}% = {f['contribution']!r}")
    print("-" * 72)
    for kind, agg_key in (("recent", "recent_aggregation"),
                          ("forecast", "forecast_aggregation")):
        agg = d[agg_key]
        print(f"{kind} point percentiles (month = window-end month):")
        for p in agg["point_percentiles"]:
            print(f"    {p['point_id']}: {p['cumulative_precip_mm']:.3f} mm "
                  f"month {p['climatology_month']:>2} -> percentile "
                  f"{p['percentile']!r} ({p['percentile_method']}, "
                  f"checksum {p['climatology']['checksum'][:12]})")
        for e in agg["exclusions"]:
            print(f"    {e['point_id']}: EXCLUDED {e['reason']} ({e['detail']})")
    print("-" * 72)
    print(f"R                 : {d['R']!r} (driver {d['R_driver_point']})")
    print(f"F                 : {d['F']!r} (driver {d['F_driver_point']})")
    print(f"D  = 0.60R+0.40F  : {d['D']!r} -> display {d['D_rounded']}")
    print(f"C  = 0.70B+0.30D  : {d['C']!r} -> display {d['C_rounded']} "
          f"band {d['current_risk_level']}")
    print(f"O7 = 0.70B+0.30F  : {d['O7']!r} -> display {d['O7_rounded']} "
          f"band {d['outlook_7d_level']}")
    print(f"direction         : {d['risk_direction']} "
          f"(previous_C={d['previous_C']}, delta_C={d['delta_C']})")
    if trend is not None:
        print(f"trend query       : {trend.status} "
              f"({len(trend.entries)} valid real snapshots)")
    print("-" * 72)
    print("top drivers (C decomposition, sum == C check):")
    total = 0.0
    for drv in d["top_drivers"]:
        total += drv["contribution_points"]
        print(f"    {drv['driver_id']:<32} {drv['driver_type']:<7} "
              f"{drv['contribution_points']!r}")
    print(f"    sum = {total!r}; |sum - C| = {abs(total - d['C']):.3e}")
    total7 = sum(x["contribution_points"] for x in d["outlook_drivers"])
    print(f"outlook drivers sum = {total7!r}; "
          f"|sum - O7| = {abs(total7 - d['O7']):.3e}")
    print("-" * 72)
    print(f"what_changed      : {d['what_changed']['status']}")
    print(f"missing_data      : {len(d['missing_data'])} record(s)")
    print("limitations:")
    for lim in d["limitations"]:
        print(f"    - {lim}")
    print("determinism       : repeated computation byte-identical OK")
    print("network calls     : 0 (offline fixture; climatology read from "
          "local G03A runtime)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
